/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package iut.fauryollivier.snoozespot.room.overridemodels

import androidx.room.Entity
import androidx.room.PrimaryKey
import iut.fauryollivier.snoozespot.api.generated.model.*


@Entity(tableName = "PostDTO")
/**
 * Room model for
 * @param id
 * @param user
 * @param content
 * @param likeCount
 * @param pictures
 * @param comments
 * @param likedByUser
 * @param createdAt
 */
data class OverridePostDTORoomModel (
    @PrimaryKey(autoGenerate = true) var roomTableId: Int,

    var id: Int,
    var user: UserDTO,
    var content: String,
    var likeCount: Int,
    var likedByUser: Boolean,
    var createdAt: String? = null,
    var pictures: List<StoredFileDTO> = emptyList(),
    var comments: List<PostCommentDTO> = emptyList(),
) {


    companion object { }

    fun toApiModel(): PostDTO = PostDTO(
        id = this.id,
        user = this.user,
        content = this.content,
        likeCount = this.likeCount,
        pictures = this.pictures,
        comments = this.comments,
        likedByUser = this.likedByUser,
        createdAt = this.createdAt,
    )
}
