/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package iut.fauryollivier.snoozespot.room.overridemodels

import androidx.room.Entity
import androidx.room.PrimaryKey
import iut.fauryollivier.snoozespot.api.generated.model.*


@Entity(tableName = "SpotDTO")
/**
 * Room model for
 * @param id
 * @param name
 * @param description
 * @param latitude
 * @param longitude
 * @param likeCount
 * @param pictures
 * @param attributes
 * @param comments
 * @param creator
 * @param rating
 * @param createdAt
 */
data class OverrideSpotDTORoomModel (
    @PrimaryKey(autoGenerate = true) var roomTableId: Int,

    var id: Int,
    var name: String,
    var description: String,
    var latitude: Double,
    var longitude: Double,
    var likeCount: Int,
    var creator: UserDTO? = null,
    var rating: Float? = null,
    var createdAt: String? = null,
    var pictures: List<StoredFileDTO> = emptyList(),
    var attributes: List<SpotAttributeDTO> = emptyList(),
    var comments: List<SpotCommentDTO> = emptyList()
    ) {

    companion object { }

    fun toApiModel(): SpotDTO = SpotDTO(
        id = this.id,
        name = this.name,
        description = this.description,
        latitude = this.latitude,
        longitude = this.longitude,
        likeCount = this.likeCount,
        pictures = this.pictures,
        attributes = this.attributes,
        comments = this.comments,
        creator = this.creator,
        rating = this.rating,
        createdAt = this.createdAt,
    )
}
