openapi: "3.1.0"
info:
  title: "snoozespot_api API"
  description: "snoozespot_api API"
  version: "1.0.0"
servers:
  - url: "https://127.0.0.1:80"
paths:
  /auth/login:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "object"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponseDTO"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
  /auth/signup:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "object"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
  /posts:
    get:
      description: ""
      parameters:
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
      responses:
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PostDTO"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Post creation failed"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PostDTO"
  /posts/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Post not found"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PostDTO"
  /spots:
    get:
      description: ""
      responses:
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/SpotDTO"
  /spots/spots/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid spot ID"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Spot not found"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SpotDTO"
  /spots/zone:
    get:
      description: ""
      parameters:
        - name: "topLeftLatitude"
          in: "query"
          required: false
          schema:
            type: "number"
        - name: "topLeftLongitude"
          in: "query"
          required: false
          schema:
            type: "number"
        - name: "bottomRightLatitude"
          in: "query"
          required: false
          schema:
            type: "number"
        - name: "bottomRightLongitude"
          in: "query"
          required: false
          schema:
            type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Missing query parameters for the zone."
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/SpotDTO"
  /users:
    get:
      description: ""
      responses:
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UserDTO"
components:
  schemas:
    UserAuthRequest:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
      required:
        - "username"
        - "password"
    AuthResponseDTO:
      type: "object"
      properties:
        accessToken:
          type: "string"
        expiresIn:
          type: "integer"
          format: "int64"
      required:
        - "accessToken"
        - "expiresIn"
    StoredFileDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        path:
          type: "string"
        type:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "name"
        - "path"
        - "type"
        - "createdAt"
    SpotAttributeDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        icon:
          nullable: true
          $ref: "#/components/schemas/StoredFileDTO"
      required:
        - "id"
        - "name"
    SpotCommentDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/UserDTO"
        description:
          type: "string"
        rating:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "user"
        - "description"
        - "rating"
        - "createdAt"
    SpotDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        creator:
          nullable: true
          $ref: "#/components/schemas/UserDTO"
        name:
          type: "string"
        description:
          type: "string"
        latitude:
          type: "number"
          format: "double"
        longitude:
          type: "number"
          format: "double"
        likeCount:
          type: "integer"
          format: "int32"
        rating:
          type: "number"
          format: "float"
          nullable: true
        createdAt:
          type: "string"
          format: "date-time"
        pictures:
          type: "array"
          items:
            $ref: "#/components/schemas/StoredFileDTO"
        attributes:
          type: "array"
          items:
            $ref: "#/components/schemas/SpotAttributeDTO"
        comments:
          type: "array"
          items:
            $ref: "#/components/schemas/SpotCommentDTO"
      required:
        - "id"
        - "name"
        - "description"
        - "latitude"
        - "longitude"
        - "likeCount"
        - "createdAt"
        - "pictures"
        - "attributes"
        - "comments"
    PostCommentDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/UserDTO"
        content:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "user"
        - "content"
        - "createdAt"
    PostDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/UserDTO"
        content:
          type: "string"
        likeCount:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        pictures:
          type: "array"
          items:
            $ref: "#/components/schemas/StoredFileDTO"
        comments:
          type: "array"
          items:
            $ref: "#/components/schemas/PostCommentDTO"
      required:
        - "id"
        - "user"
        - "content"
        - "likeCount"
        - "createdAt"
        - "pictures"
        - "comments"
    UserDTO:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
        username:
          type: "string"
        email:
          type: "string"
          nullable: true
        profilePicture:
          nullable: true
          $ref: "#/components/schemas/StoredFileDTO"
        karma:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        spots:
          type: "array"
          items:
            $ref: "#/components/schemas/SpotDTO"
        posts:
          type: "array"
          items:
            $ref: "#/components/schemas/PostDTO"
        following:
          type: "array"
          items:
            $ref: "#/components/schemas/UserDTO"
        followers:
          type: "array"
          items:
            $ref: "#/components/schemas/UserDTO"
      required:
        - "uuid"
        - "username"
        - "karma"
        - "createdAt"
        - "spots"
        - "posts"
        - "following"
        - "followers"
    CreatePostRequest:
      type: "object"
      properties:
        content:
          type: "string"
      required:
        - "content"