openapi: "3.1.0"
info:
  title: "snoozespot_api API"
  description: "snoozespot_api API"
  version: "1.0.0"
servers:
  - url: "https://snoozespot_api"
paths:
  /protected/route/basic:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /protected/route/form:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /articles:
    get:
      description: ""
      parameters:
        - name: "sort"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK <br> Get all articles ..."
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /name:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DataTest"
              examples:
                Example#1:
                  description: ""
                  value:
                    name: "Ktor"
  /post/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK <br> Respond with the mock post"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Post"
              examples:
                Example#1:
                  description: "Mock data for the post"
                  value:
                    id: "null"
                    userId: 1
                    content: "This is a sample post content"
                    likeCount: 123
                    canBeDisplayed: true
                    createdAt: "null"
                    deletedAt: "null"
  /spot/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Spot"
              examples:
                Example#1:
                  description: ""
                  value:
                    id: "null"
                    creatorId: 42
                    name: "Chill Spot in the Woods"
                    description: "A quiet and peaceful place surrounded by trees."
                    latitude: 45.764043
                    longitude: 4.835659
                    canBeDisplayed: true
                    createdAt: "null"
                    deletedAt: "null"
  /users:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
  /json/kotlinx-serialization:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_String"
components:
  schemas:
    DataTest:
      type: "object"
      properties:
        name:
          type: "string"
      required:
        - "name"
    Post:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        userId:
          type: "integer"
          format: "int32"
        content:
          type: "string"
        likeCount:
          type: "integer"
          format: "int32"
          default: "0"
        canBeDisplayed:
          type: "boolean"
        createdAt:
          type: "string"
          format: "date-time"
        deletedAt:
          type: "string"
          format: "date-time"
          nullable: true
      required:
        - "id"
        - "userId"
        - "content"
        - "likeCount"
        - "canBeDisplayed"
        - "createdAt"
    Spot:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        creatorId:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        description:
          type: "string"
        latitude:
          type: "number"
          format: "double"
        longitude:
          type: "number"
          format: "double"
        canBeDisplayed:
          type: "boolean"
        createdAt:
          type: "string"
          format: "date-time"
        deletedAt:
          type: "string"
          format: "date-time"
          nullable: true
      required:
        - "id"
        - "creatorId"
        - "name"
        - "description"
        - "latitude"
        - "longitude"
        - "canBeDisplayed"
        - "createdAt"
    Map:
      type: "object"
      properties: { }
    Map_String:
      type: "string"