openapi: "3.1.0"
info:
  title: "snoozespot_api API"
  description: "snoozespot_api API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /posts:
    get:
      description: ""
      parameters:
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Post"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "object"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Post creation failed"
  /posts/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Post not found"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Post"
  /users:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
  /auth/login:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /auth/signup:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    StoredFile:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        path:
          type: "string"
        type:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "name"
        - "path"
        - "type"
        - "createdAt"
    SpotAttribute:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        icon:
          nullable: true
          $ref: "#/components/schemas/StoredFile"
      required:
        - "id"
        - "name"
    SpotComment:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/User"
        description:
          type: "string"
        rating:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "user"
        - "description"
        - "rating"
        - "createdAt"
    Spot:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        creator:
          $ref: "#/components/schemas/User"
        name:
          type: "string"
        description:
          type: "string"
        latitude:
          type: "number"
          format: "double"
        longitude:
          type: "number"
          format: "double"
        canBeDisplayed:
          type: "integer"
          format: "int32"
        likeCount:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        pictures:
          type: "array"
          items:
            $ref: "#/components/schemas/StoredFile"
        attributes:
          type: "array"
          items:
            $ref: "#/components/schemas/SpotAttribute"
        comments:
          type: "array"
          items:
            $ref: "#/components/schemas/SpotComment"
      required:
        - "id"
        - "creator"
        - "name"
        - "description"
        - "latitude"
        - "longitude"
        - "canBeDisplayed"
        - "likeCount"
        - "createdAt"
        - "pictures"
        - "attributes"
        - "comments"
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        username:
          type: "string"
        email:
          type: "string"
          nullable: true
        profilePicture:
          nullable: true
          $ref: "#/components/schemas/StoredFile"
        karma:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        spots:
          type: "array"
          items:
            $ref: "#/components/schemas/Spot"
        posts:
          type: "array"
          items:
            $ref: "#/components/schemas/Post"
        following:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
        follower:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
      required:
        - "id"
        - "username"
        - "karma"
        - "createdAt"
        - "spots"
        - "posts"
        - "following"
        - "follower"
    PostComment:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/User"
        content:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "user"
        - "content"
        - "createdAt"
    Post:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        user:
          $ref: "#/components/schemas/User"
        content:
          type: "string"
        likeCount:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        pictures:
          type: "array"
          items:
            $ref: "#/components/schemas/StoredFile"
        comments:
          type: "array"
          items:
            $ref: "#/components/schemas/PostComment"
      required:
        - "id"
        - "user"
        - "content"
        - "likeCount"
        - "createdAt"
        - "pictures"
        - "comments"
    CreatePostRequest:
      type: "object"
      properties:
        content:
          type: "string"
      required:
        - "content"
    UserAuthRequest:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
      required:
        - "username"
        - "password"
    AuthResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
        expiresIn:
          type: "integer"
          format: "int64"
      required:
        - "accessToken"
        - "expiresIn"